<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class popula_profissional extends Seeder
{
    public function run(): void
    {
        DB::table('profissionais')->insert([
            [
                'cpf' => '123.456.789-01',
                'nome' => 'Ademar Santos',
                'especializacao' => 'Fonoaudiólogo',
                'celular' => '11-1111-1111',
                'email' => 'ademar@example.com',
                'cep' => '11111-111',
                'bairro' => 'Centro',
                'logradouro' => 'Rua Teste',
                'numero' => '1',
                'complemento' => 'Apto 1',
                'cidade' => 'São Paulo',
                'uf' => 'SP',
            ],
            [
                'cpf' => '234.567.890-12',
                'nome' => 'Maria Oliveira',
                'especializacao' => 'Nutricionista',
                'celular' => '22-2222-2222',
                'email' => 'maria@example.com',
                'cep' => '22222-222',
                'bairro' => 'Bairro Novo',
                'logradouro' => 'Avenida Principal',
                'numero' => '10',
                'complemento' => 'Casa 2',
                'cidade' => 'Rio de Janeiro',
                'uf' => 'RJ',
            ],
            [
                'cpf' => '345.678.901-23',
                'nome' => 'Carlos Santos',
                'especializacao' => 'Psicólogo',
                'celular' => '33-3333-3333',
                'email' => 'carlos@example.com',
                'cep' => '33333-333',
                'bairro' => 'Bela Vista',
                'logradouro' => 'Rua das Flores',
                'numero' => '5',
                'complemento' => 'Casa 3',
                'cidade' => 'Belo Horizonte',
                'uf' => 'MG',
            ],
            [
                'cpf' => '456.789.012-34',
                'nome' => 'Ana Pereira',
                'especializacao' => 'Psicólogo',
                'celular' => '44-4444-4444',
                'email' => 'ana@example.com',
                'cep' => '44444-444',
                'bairro' => 'Jardim São Paulo',
                'logradouro' => 'Rua das Árvores',
                'numero' => '20',
                'complemento' => 'Casa 5',
                'cidade' => 'Curitiba',
                'uf' => 'PR',
            ],
            [
                'cpf' => '567.890.123-45',
                'nome' => 'Paulo Lima',
                'especializacao' => 'Dentista',
                'celular' => '55-5555-5555',
                'email' => 'paulo@example.com',
                'cep' => '55555-555',
                'bairro' => 'Centro',
                'logradouro' => 'Rua Principal',
                'numero' => '30',
                'complemento' => 'Sala 10',
                'cidade' => 'Porto Alegre',
                'uf' => 'RS',
            ],
            [
                'cpf' => '678.901.234-56',
                'nome' => 'Juliana Silva',
                'especializacao' => 'Pediatra',
                'celular' => '66-6666-6666',
                'email' => 'juliana@example.com',
                'cep' => '66666-666',
                'bairro' => 'Jardim das Flores',
                'logradouro' => 'Avenida das Palmeiras',
                'numero' => '40',
                'complemento' => 'Casa 6',
                'cidade' => 'Salvador',
                'uf' => 'BA',
            ],
            [
                'cpf' => '789.012.345-67',
                'nome' => 'Ricardo Almeida',
                'especializacao' => 'Ortopedista',
                'celular' => '77-7777-7777',
                'email' => 'ricardo@example.com',
                'cep' => '77777-777',
                'bairro' => 'Vila Nova',
                'logradouro' => 'Rua dos Coqueiros',
                'numero' => '50',
                'complemento' => 'Casa 8',
                'cidade' => 'Fortaleza',
                'uf' => 'CE',
            ],
            [
                'cpf' => '890.123.456-78',
                'nome' => 'Camila Costa',
                'especializacao' => 'Cardiologista',
                'celular' => '88-8888-8888',
                'email' => 'camila@example.com',
                'cep' => '88888-888',
                'bairro' => 'Bairro Novo',
                'logradouro' => 'Avenida dos Girassóis',
                'numero' => '60',
                'complemento' => 'Apartamento 15',
                'cidade' => 'Recife',
                'uf' => 'PE',
            ],
            [
                'cpf' => '901.234.567-89',
                'nome' => 'Lucas Fernandes',
                'especializacao' => 'Dermatologista',
                'celular' => '99-9999-9999',
                'email' => 'lucas@example.com',
                'cep' => '99999-999',
                'bairro' => 'Centro',
                'logradouro' => 'Rua das Oliveiras',
                'numero' => '70',
                'complemento' => 'Sala 20',
                'cidade' => 'Brasília',
                'uf' => 'DF',
            ],
            [
                'cpf' => '012.345.678-90',
                'nome' => 'Fernanda Lima',
                'especializacao' => 'Ginecologista',
                'celular' => '00-0000-0000',
                'email' => 'fernanda@example.com',
                'cep' => '00000-000',
                'bairro' => 'Jardim das Rosas',
                'logradouro' => 'Avenida dos Lírios',
                'numero' => '80',
                'complemento' => 'Casa 10',
                'cidade' => 'Manaus',
                'uf' => 'AM',
            ],
            [
                'cpf' => '123.456.789-10',
                'nome' => 'Rafaela Silva',
                'especializacao' => 'Oftalmologista',
                'celular' => '11-1111-1111',
                'email' => 'rafaela@example.com',
                'cep' => '11111-111',
                'bairro' => 'Centro',
                'logradouro' => 'Rua dos Pinheiros',
                'numero' => '90',
                'complemento' => 'Apartamento 25',
                'cidade' => 'Porto Velho',
                'uf' => 'RO',
            ],
            [
                'cpf' => '234.567.890-11',
                'nome' => 'Roberto Souza',
                'especializacao' => 'Psiquiatra',
                'celular' => '22-2222-2222',
                'email' => 'roberto@example.com',
                'cep' => '22222-222',
                'bairro' => 'Bairro Novo',
                'logradouro' => 'Rua das Acácias',
                'numero' => '100',
                'complemento' => 'Bloco B, Ap 30',
                'cidade' => 'Natal',
                'uf' => 'RN',
            ],
            [
                'cpf' => '345.678.901-12',
                'nome' => 'Patricia Oliveira',
                'especializacao' => 'Fisioterapeuta',
                'celular' => '33-3333-3333',
                'email' => 'patricia@example.com',
                'cep' => '33333-333',
                'bairro' => 'Bela Vista',
                'logradouro' => 'Avenida das Flores',
                'numero' => '110',
                'complemento' => 'Casa 15',
                'cidade' => 'Florianópolis',
                'uf' => 'SC',
            ],
        ]);        
    }    
}
