<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class popula_consulta extends Seeder
{
    public function run(): void
    {
        DB::table('consultas')->insert([
            [
                'cliente_id' => '1',
                'profissional_id' => '1',
                'sala' => '1',
                'horario' => '10:30',
                'cid' => 'J93 - Pneumotórax',
                'frequencia' => 'Presente',
                'especialidade' => 'Cirurgião Torácico',
                'plano' => 'UNIMED',
                'nivel' => 'Gold',
                'dia_semana' => 'Segunda-Feira',
                'data_consulta' => '2024-03-25',
            ],
            [
                'cliente_id' => '3',
                'profissional_id' => '9',
                'sala' => '3',
                'horario' => '14:00',
                'cid' => 'G40 - Epilepsia',
                'frequencia' => 'Presente',
                'especialidade' => 'Neurologista',
                'plano' => 'SULAMÉRICA',
                'nivel' => 'Básico',
                'dia_semana' => 'Quarta-Feira',
                'data_consulta' => '2024-03-28',
            ],
            [
                'cliente_id' => '4',
                'profissional_id' => '10',
                'sala' => '4',
                'horario' => '11:30',
                'cid' => 'J44 - Outras doenças pulmonares obstructivas crônicas',
                'frequencia' => 'Presente',
                'especialidade' => 'Pneumologista',
                'plano' => 'GOLDEN CROSS',
                'nivel' => 'Top',
                'dia_semana' => 'Quinta-Feira',
                'data_consulta' => '2024-03-30',
            ],
            [
                'cliente_id' => '5',
                'profissional_id' => '1',
                'sala' => '1',
                'horario' => '15:00',
                'cid' => 'K55 - Sangramento anal',
                'frequencia' => 'Presente',
                'especialidade' => 'Proctologista',
                'plano' => 'UNIMED',
                'nivel' => 'Gold',
                'dia_semana' => 'Sexta-Feira',
                'data_consulta' => '2024-03-31',
            ],
            [
                'cliente_id' => '5',
                'profissional_id' => '2',
                'sala' => '2',
                'horario' => '10:45',
                'cid' => 'G47 - Distúrbios do sono',
                'frequencia' => 'Falta',
                'especialidade' => 'Psiquiatra',
                'plano' => 'AMIL',
                'nivel' => 'Premium',
                'dia_semana' => 'Segunda-Feira',
                'data_consulta' => '2024-04-01',
            ],
            [
                'cliente_id' => '1',
                'profissional_id' => '2',
                'sala' => '2',
                'horario' => '13:45',
                'cid' => 'A09 - Diarréia e gastroenterite de origem infecciosa presumível',
                'frequencia' => 'Falta',
                'especialidade' => 'Nutricionista',
                'plano' => 'AMIL',
                'nivel' => 'Premium',
                'dia_semana' => 'Terça-Feira',
                'data_consulta' => '2024-03-26',
            ],
            [
                'cliente_id' => '1',
                'profissional_id' => '3',
                'sala' => '3',
                'horario' => '09:00',
                'cid' => 'F32 - Episódios depressivos',
                'frequencia' => 'Presente',
                'especialidade' => 'Psicólogo',
                'plano' => 'SULAMÉRICA',
                'nivel' => 'Básico',
                'dia_semana' => 'Quarta-Feira',
                'data_consulta' => '2024-03-27',
            ],
            [
                'cliente_id' => '1',
                'profissional_id' => '4',
                'sala' => '4',
                'horario' => '16:20',
                'cid' => 'F41 - Transtornos de ansiedade',
                'frequencia' => 'Falta Justificada',
                'especialidade' => 'Psicólogo',
                'plano' => 'GOLDEN CROSS',
                'nivel' => 'Top',
                'dia_semana' => 'Sexta-Feira',
                'data_consulta' => '2024-03-29',
            ],
            [
                'cliente_id' => '2',
                'profissional_id' => '5',
                'sala' => '1',
                'horario' => '11:00',
                'cid' => 'L03 - Lúpus eritematoso discoide',
                'frequencia' => 'Presente',
                'especialidade' => 'Dermatologista',
                'plano' => 'UNIMED',
                'nivel' => 'Gold',
                'dia_semana' => 'Segunda-Feira',
                'data_consulta' => '2024-03-25',
            ],
            [
                'cliente_id' => '2',
                'profissional_id' => '6',
                'sala' => '2',
                'horario' => '14:30',
                'cid' => 'K85 - Pancreatite aguda',
                'frequencia' => 'Presente',
                'especialidade' => 'Gastroenterologista',
                'plano' => 'AMIL',
                'nivel' => 'Premium',
                'dia_semana' => 'Terça-Feira',
                'data_consulta' => '2024-03-26',
            ],
            [
                'cliente_id' => '2',
                'profissional_id' => '7',
                'sala' => '3',
                'horario' => '10:00',
                'cid' => 'N19 - Insuficiência renal aguda',
                'frequencia' => 'Presente',
                'especialidade' => 'Nefrologista',
                'plano' => 'SULAMÉRICA',
                'nivel' => 'Básico',
                'dia_semana' => 'Quarta-Feira',
                'data_consulta' => '2024-03-27',
            ],
            [
                'cliente_id' => '2',
                'profissional_id' => '8',
                'sala' => '4',
                'horario' => '17:00',
                'cid' => 'R55 - Sincope e colapso',
                'frequencia' => 'Falta',
                'especialidade' => 'Cardiologista',
                'plano' => 'GOLDEN CROSS',
                'nivel' => 'Top',
                'dia_semana' => 'Sexta-Feira',
                'data_consulta' => '2024-03-29',
            ],
            [
                'cliente_id' => '3',
                'profissional_id' => '9',
                'sala' => '1',
                'horario' => '09:30',
                'cid' => 'I50 - Insuficiência cardíaca congestiva',
                'frequencia' => 'Presente',
                'especialidade' => 'Cardiologista',
                'plano' => 'UNIMED',
                'nivel' => 'Gold',
                'dia_semana' => 'Segunda-Feira',
                'data_consulta' => '2024-03-25',
            ],
            [
                'cliente_id' => '3',
                'profissional_id' => '10',
                'sala' => '2',
                'horario' => '15:15',
                'cid' => 'C20 - Neoplasia maligna do reto',
                'frequencia' => 'Presente',
                'especialidade' => 'Oncologista',
                'plano' => 'AMIL',
                'nivel' => 'Premium',
                'dia_semana' => 'Terça-Feira',
                'data_consulta' => '2024-03-26',
            ],
        ]);
    }
}
