<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class popula_cliente extends Seeder
{
    public function run(): void
    {
        DB::table('clientes')->insert([
            [
                'cpf' => '123.456.789-01',
                'nome' => 'João da Silva',
                'celular' => '11-1111-1111',
                'email' => 'joao@example.com',
                'cep' => '11111-111',
                'bairro' => 'Centro',
                'logradouro' => 'Rua Teste',
                'numero' => '1',
                'complemento' => 'Apto 1',
                'cidade' => 'São Paulo',
                'uf' => 'SP',
            ],
            [
                'cpf' => '234.567.890-12',
                'nome' => 'Maria Oliveira',
                'celular' => '22-2222-2222',
                'email' => 'maria@example.com',
                'cep' => '22222-222',
                'bairro' => 'Bairro Novo',
                'logradouro' => 'Avenida Principal',
                'numero' => '10',
                'complemento' => 'Casa 2',
                'cidade' => 'Rio de Janeiro',
                'uf' => 'RJ',
            ],
            [
                'cpf' => '345.678.901-23',
                'nome' => 'Carlos Santos',
                'celular' => '33-3333-3333',
                'email' => 'carlos@example.com',
                'cep' => '33333-333',
                'bairro' => 'Bela Vista',
                'logradouro' => 'Rua das Flores',
                'numero' => '5',
                'complemento' => 'Casa 3',
                'cidade' => 'Belo Horizonte',
                'uf' => 'MG',
            ],
            [
                'cpf' => '456.789.012-34',
                'nome' => 'Ana Pereira',
                'celular' => '44-4444-4444',
                'email' => 'ana@example.com',
                'cep' => '44444-444',
                'bairro' => 'Jardim São Paulo',
                'logradouro' => 'Rua das Árvores',
                'numero' => '20',
                'complemento' => 'Casa 5',
                'cidade' => 'Curitiba',
                'uf' => 'PR',
            ],
            [
                'cpf' => '567.890.123-45',
                'nome' => 'Pedro Souza',
                'celular' => '55-5555-5555',
                'email' => 'pedro@example.com',
                'cep' => '55555-555',
                'bairro' => 'Centro',
                'logradouro' => 'Avenida Central',
                'numero' => '15',
                'complemento' => 'Apto 10',
                'cidade' => 'Porto Alegre',
                'uf' => 'RS',
            ],
            [
                'cpf' => '678.901.234-56',
                'nome' => 'Paula Lima',
                'celular' => '66-6666-6666',
                'email' => 'paula@example.com',
                'cep' => '66666-666',
                'bairro' => 'Jardim Botânico',
                'logradouro' => 'Rua das Palmeiras',
                'numero' => '30',
                'complemento' => 'Casa 8',
                'cidade' => 'Florianópolis',
                'uf' => 'SC',
            ],
            [
                'cpf' => '789.012.345-67',
                'nome' => 'Fernando Mendes',
                'celular' => '77-7777-7777',
                'email' => 'fernando@example.com',
                'cep' => '77777-777',
                'bairro' => 'Jardim das Flores',
                'logradouro' => 'Rua dos Girassóis',
                'numero' => '40',
                'complemento' => 'Casa 12',
                'cidade' => 'Goiânia',
                'uf' => 'GO',
            ],
            [
                'cpf' => '890.123.456-78',
                'nome' => 'Aline Costa',
                'celular' => '88-8888-8888',
                'email' => 'aline@example.com',
                'cep' => '88888-888',
                'bairro' => 'Vila Nova',
                'logradouro' => 'Rua das Violetas',
                'numero' => '50',
                'complemento' => 'Casa 15',
                'cidade' => 'Salvador',
                'uf' => 'BA',
            ],
            [
                'cpf' => '901.234.567-89',
                'nome' => 'Rafael Almeida',
                'celular' => '99-9999-9999',
                'email' => 'rafael@example.com',
                'cep' => '99999-999',
                'bairro' => 'Parque Industrial',
                'logradouro' => 'Avenida dos Eucaliptos',
                'numero' => '60',
                'complemento' => 'Casa 20',
                'cidade' => 'Recife',
                'uf' => 'PE',
            ],
            [
                'cpf' => '012.345.678-90',
                'nome' => 'Luciana Oliveira',
                'celular' => '00-0000-0000',
                'email' => 'luciana@example.com',
                'cep' => '00000-000',
                'bairro' => 'Alvorada',
                'logradouro' => 'Rua dos Sabiás',
                'numero' => '70',
                'complemento' => 'Casa 25',
                'cidade' => 'Brasília',
                'uf' => 'DF',
            ],
            [
                'cpf' => '123.567.890-12',
                'nome' => 'Gustavo Silva',
                'celular' => '11-1111-1111',
                'email' => 'gustavo@example.com',
                'cep' => '11111-111',
                'bairro' => 'Centro',
                'logradouro' => 'Rua Teste',
                'numero' => '1',
                'complemento' => 'Apto 1',
                'cidade' => 'São Paulo',
                'uf' => 'SP',
            ],
            [
                'cpf' => '234.678.901-23',
                'nome' => 'Renata Santos',
                'celular' => '22-2222-2222',
                'email' => 'renata@example.com',
                'cep' => '22222-222',
                'bairro' => 'Bairro Novo',
                'logradouro' => 'Avenida Principal',
                'numero' => '10',
                'complemento' => 'Casa 2',
                'cidade' => 'Rio de Janeiro',
                'uf' => 'RJ',
            ],
            [
                'cpf' => '345.789.012-34',
                'nome' => 'Felipe Pereira',
                'celular' => '33-3333-3333',
                'email' => 'felipe@example.com',
                'cep' => '33333-333',
                'bairro' => 'Bela Vista',
                'logradouro' => 'Rua das Flores',
                'numero' => '5',
                'complemento' => 'Casa 3',
                'cidade' => 'Belo Horizonte',
                'uf' => 'MG',
            ],
            [
                'cpf' => '123.456.789-11',
                'nome' => 'João da Silva',
                'celular' => '11-1111-1113',
                'email' => 'joao@example.com',
                'cep' => '11111-111',
                'bairro' => 'Centro',
                'logradouro' => 'Rua Teste',
                'numero' => '1',
                'complemento' => 'Apto 1',
                'cidade' => 'São Paulo',
                'uf' => 'SP',
            ],
            [
                'cpf' => '233.567.890-12',
                'nome' => 'Maria Oliveira',
                'celular' => '22-2222-2242',
                'email' => 'maria@example.com',
                'cep' => '22222-222',
                'bairro' => 'Bairro Novo',
                'logradouro' => 'Avenida Principal',
                'numero' => '10',
                'complemento' => 'Casa 2',
                'cidade' => 'Rio de Janeiro',
                'uf' => 'RJ',
            ],
            [
                'cpf' => '345.678.901-25',
                'nome' => 'Carlos Santos',
                'celular' => '33-3335-3333',
                'email' => 'carlos@example.com',
                'cep' => '33333-333',
                'bairro' => 'Bela Vista',
                'logradouro' => 'Rua das Flores',
                'numero' => '5',
                'complemento' => 'Casa 3',
                'cidade' => 'Belo Horizonte',
                'uf' => 'MG',
            ],
            [
                'cpf' => '456.789.212-34',
                'nome' => 'Ana Pereira',
                'celular' => '44-4844-4444',
                'email' => 'ana@example.com',
                'cep' => '44444-444',
                'bairro' => 'Jardim São Paulo',
                'logradouro' => 'Rua das Árvores',
                'numero' => '20',
                'complemento' => 'Casa 5',
                'cidade' => 'Curitiba',
                'uf' => 'PR',
            ],
            [
                'cpf' => '567.890.523-45',
                'nome' => 'Pedro Souza',
                'celular' => '55-5555-5555',
                'email' => 'pedro@example.com',
                'cep' => '55555-555',
                'bairro' => 'Centro',
                'logradouro' => 'Avenida Central',
                'numero' => '15',
                'complemento' => 'Apto 10',
                'cidade' => 'Porto Alegre',
                'uf' => 'RS',
            ],
            [
                'cpf' => '678.901.234-59',
                'nome' => 'Paula Lima',
                'celular' => '66-6666-6666',
                'email' => 'paula@example.com',
                'cep' => '66666-666',
                'bairro' => 'Jardim Botânico',
                'logradouro' => 'Rua das Palmeiras',
                'numero' => '30',
                'complemento' => 'Casa 8',
                'cidade' => 'Florianópolis',
                'uf' => 'SC',
            ],
            [
                'cpf' => '789.012.385-67',
                'nome' => 'Fernando Mendes',
                'celular' => '77-7777-7777',
                'email' => 'fernando@example.com',
                'cep' => '77777-777',
                'bairro' => 'Jardim das Flores',
                'logradouro' => 'Rua dos Girassóis',
                'numero' => '40',
                'complemento' => 'Casa 12',
                'cidade' => 'Goiânia',
                'uf' => 'GO',
            ],
            [
                'cpf' => '890.128.456-78',
                'nome' => 'Aline Costa',
                'celular' => '88-8888-8888',
                'email' => 'aline@example.com',
                'cep' => '88888-888',
                'bairro' => 'Vila Nova',
                'logradouro' => 'Rua das Violetas',
                'numero' => '50',
                'complemento' => 'Casa 15',
                'cidade' => 'Salvador',
                'uf' => 'BA',
            ],
            [
                'cpf' => '901.234.997-89',
                'nome' => 'Rafael Almeida',
                'celular' => '99-9999-9999',
                'email' => 'rafael@example.com',
                'cep' => '99999-999',
                'bairro' => 'Parque Industrial',
                'logradouro' => 'Avenida dos Eucaliptos',
                'numero' => '60',
                'complemento' => 'Casa 20',
                'cidade' => 'Recife',
                'uf' => 'PE',
            ],
            [
                'cpf' => '112.345.678-90',
                'nome' => 'Luciana Oliveira',
                'celular' => '00-0000-0000',
                'email' => 'luciana@example.com',
                'cep' => '00000-000',
                'bairro' => 'Alvorada',
                'logradouro' => 'Rua dos Sabiás',
                'numero' => '70',
                'complemento' => 'Casa 25',
                'cidade' => 'Brasília',
                'uf' => 'DF',
            ],
            [
                'cpf' => '123.567.890-52',
                'nome' => 'Gustavo Silva',
                'celular' => '11-1111-1111',
                'email' => 'gustavo@example.com',
                'cep' => '11111-111',
                'bairro' => 'Centro',
                'logradouro' => 'Rua Teste',
                'numero' => '1',
                'complemento' => 'Apto 1',
                'cidade' => 'São Paulo',
                'uf' => 'SP',
            ],
            [
                'cpf' => '234.678.961-23',
                'nome' => 'Renata Santos',
                'celular' => '22-2222-2222',
                'email' => 'renata@example.com',
                'cep' => '22222-222',
                'bairro' => 'Bairro Novo',
                'logradouro' => 'Avenida Principal',
                'numero' => '10',
                'complemento' => 'Casa 2',
                'cidade' => 'Rio de Janeiro',
                'uf' => 'RJ',
            ],
            [
                'cpf' => '345.989.012-34',
                'nome' => 'Felipe Pereira',
                'celular' => '33-3333-3333',
                'email' => 'felipe@example.com',
                'cep' => '33333-333',
                'bairro' => 'Bela Vista',
                'logradouro' => 'Rua das Flores',
                'numero' => '5',
                'complemento' => 'Casa 3',
                'cidade' => 'Belo Horizonte',
                'uf' => 'MG',
            ]
        ]);
    }
}
